### ISSUE TITLE
Failed compile with gcc 15.2

### ISSUE THREAD

**Issue by oodame** [facebook/mvfst#419]
When compiling with gcc 15.2, it emits error like this
```
In file included from /home/workspace/third_party_builder/source/mvfst-2025.12.29.00/quic/congestion_control/PacerFactory.cpp:8:
/home/workspace/third_party_builder/source/mvfst-2025.12.29.00/quic/congestion_control/PacerFactory.h:24:5: error: 'uint64_t' has not been declared
   24 |     uint64_t minCwndInMss);
      |     ^~~~~~~~
/home/workspace/third_party_builder/source/mvfst-2025.12.29.00/quic/congestion_control/PacerFactory.h:11:1: note: 'uint64_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
   10 | #include <memory>
  +++ |+#include <cstdint>
   11 |
```
